on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

name: Main Workflow

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11.0.3'  # Specify the desired Java version

      - name: Download SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
          unzip sonar-scanner-cli-4.0.0.1744-linux.zip -d /opt/sonar-scanner

      - name: Add SonarScanner to PATH
        run: echo "PATH=$PATH:/opt/sonar-scanner/bin" >> $GITHUB_ENV

      - name: SonarQube Scan
        run: |
          sonar-scanner -Dsonar.projectKey=advance_git_sonarqube_Scan:master -Dsonar.projectVersion=1.3 -Dsonar.projectName=advance_git_sonarqube_Scan -Dsonar.login=6de6745d90b35fcc4303342afcbea7c8674a22a3 -Dsonar.sources=src -Dsonar.host.url=https://8e93-103-81-78-10.ngrok-free.app -Dsonar.java.binaries=target/classes -Dsonar.jacoco.reportPaths=target/jacoco.exec -Dsonar.pdf.issue.details=BUG,CODE_SMELL,VULNERABILITY -Dsonar.pdf.other.metrics=uncovered_lines -Dsonar.pdf.skip=false
